Traceback (most recent call last):
  File "/home/kaustubh/Code3/cov_tester.py", line 134, in <module>
    main(data_path=data_path,batch_size=batch_size,num_epochs=num_epochs,learning_rate=learning_rate,model_path=model_path)
  File "/home/kaustubh/Code3/cov_tester.py", line 83, in main
    ind = (losses<set_eps).sum()
TypeError: '<' not supported between instances of 'Tensor' and 'str'