
**Starting data processing**
48626
Traceback (most recent call last):
  File "/raid/ganesh/racha_suraj/SF_test/Power-Mechanism-new/Adult_income/test_income.py", line 152, in <module>
    os.mkdir(dirpth)
FileNotFoundError: [Errno 2] No such file or directory: './Embeddings/adult_512_1'
 ** Creating embeddings **
  38900
 ** Creating embeddings **
  38900