Traceback (most recent call last):
  File "/home/kaustubh/Code3/cov_tester.py", line 136, in <module>
    main(data_path=data_path,batch_size=batch_size,num_epochs=num_epochs,learning_rate=learning_rate,model_path=model_path)
  File "/home/kaustubh/Code3/cov_tester.py", line 82, in main
    print(type(set_eps))
UnboundLocalError: local variable 'set_eps' referenced before assignment